_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.9
            "6": 4.50.3
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 16
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 512
compile:
    value: false
dataset:
    value: customer_service
decay_lr:
    value: true
device:
    value: cuda
dropout:
    value: 0.2
dtype:
    value: bfloat16
eval_interval:
    value: 200
eval_iters:
    value: 50
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 5e-05
log_interval:
    value: 10
lr_decay_iters:
    value: 5000
max_iters:
    value: 5000
min_lr:
    value: 5e-06
n_embd:
    value: 384
n_head:
    value: 6
n_layer:
    value: 6
out_dir:
    value: out-sentiment
wandb_log:
    value: true
wandb_project:
    value: sentiment-analysis
wandb_run_name:
    value: gpt-sentiment
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
